- hosts: all
  collections:
    - azure.azcollection
  tasks:
    - name: Clean a resource group
      azure_rm_resourcegroup:
        name: "{{ azure_resource_group }}"
        location: "{{ azure_location}}"
        state: absent
