- hosts: all
  collections:
    - azure.azcollection
  tasks:
    - name: debug
      debug:
        msg: "{{ inventory_dir }}"
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ azure_resource_group }}"
        location: "{{ azure_location}}"
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_nw_name }}"
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_subnet_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ azure_nw_name }}"
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ azure_resource_group }}"
        allocation_method: Static
        name: "{{ azure_vip_name }}"
    - name: Create Network Security Group that allows PostgreSQL traffic
      azure_rm_securitygroup:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_sg_name }}"
        rules:
          - name: PostgreSQL_rw
            protocol: Tcp
            destination_port_range: 5432
            access: Allow
            priority: 1001
            direction: Inbound
          - name: PostgreSQL_ro
            protocol: Tcp
            destination_port_range: 5433
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Create a load balancer
      azure_rm_loadbalancer:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_lb_name }}"
        location: "{{ azure_location }}"
        frontend_ip_configurations:
          - name: "{{ azure_lbfe_name }}"
            public_ip_address: "{{ azure_vip_name }}"
        backend_address_pools:
          - name: "{{ azure_lbbe_name }}"
        probes:
          - name: "probe_{{ azure_lb_name }}_0"
            port: 5432
            interval: 10
            fail_count: 3
          - name: "probe_{{ azure_lb_name }}_1"
            port: 25432
            interval: 10
            fail_count: 3
        load_balancing_rules:
          - name: "rule_{{ azure_lb_name }}_1"
            frontend_ip_configuration: "{{ azure_lbfe_name }}"
            backend_address_pool: "{{ azure_lbbe_name }}"
            frontend_port: 5432
            backend_port: 25432
            load_distribution: Default
            probe: "probe_{{ azure_lb_name }}_0"
          - name: "rule_{{ azure_lb_name }}_2"
            frontend_ip_configuration: "{{ azure_lbfe_name }}"
            backend_address_pool: "{{ azure_lbbe_name }}"
            frontend_port: 5433
            backend_port: 5432
            load_distribution: Default
            probe: "probe_{{ azure_lb_name }}_1"
    - name: Read shs public key
      shell: "cat ~/.ssh/id_rsa.pub"
      register: public_ssh

    - name: Create VM scaleset
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_vmss_name }}"
        admin_username: "{{ ansible_user_id }}"
        single_placement_group: true
        vm_size: "{{azure_vmss_vm_size}}"
        capacity: "{{ azure_vmss_vm_count }}"
        virtual_network_name: "{{ azure_nw_name }}"
        subnet_name: "{{ azure_subnet_name }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ public_ssh.stdout }}"
        upgrade_policy: Manual
        tier: Standard
        managed_disk_type: "{{ azure_vm_disk_type }}"
        os_disk_caching: ReadWrite
        image:
          offer: CentOS
          publisher: OpenLogic
          version: latest
          sku: 7.5
        load_balancer: "{{ azure_lb_name }}"
        data_disks:
          - lun: 0
            disk_size_gb: "{{ azure_data_gb }}"
            managed_disk_type: "{{ azure_data_disk_type }}"
          - lun: 1
            disk_size_gb: "{{ azure_wal_gb }}"
            managed_disk_type: "{{ azure_wal_disk_type }}"
