---
# tasks file for chainsmith
#- name: debug
#  debug:
#    msg: "{{ chainsmith_servers }}"

- name: install
  import_tasks: install.yml

- name: Check if output files exist
  stat:
    path: "{{ inventory_dir }}/group_vars/all/certs.yml"
  register: existing

- name: Display
  debug:
    msg: "'{{ inventory_dir }}/group_vars/all/certs.yml' already exists"
  when: "existing.stat.exists"

- name: run chainsmith
  import_tasks: run.yml
  when: not existing.stat.exists
