---
# tasks file for chainsmith
- name: Create temporary chainsmith config file
  ansible.builtin.tempfile:
    state: file
    suffix: chainsmith
  register: chainsmith_config

- name: create chainsmith_config
  copy:
    dest: "{{ chainsmith_config.path }}"
    content: "{{ chainsmith_body | to_nice_json }}"

#- name: path to config file
#  debug:
#    var: chainsmith_config.path

- name: run chainsmith
  shell:
    cmd: "{{ chainsmith_cmd }}"
  environment:
    CHAINSMITH_CONFIG: "{{ chainsmith_config.path }}"
  register: chainsmith_out

- name: create certs config file in inventory
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
  loop:
    - dest: "{{ inventory_dir }}/group_vars/all/certs.yml"
      content: "{{ chainsmith_out.stdout }}"
    - dest: "{{ inventory_dir }}/group_vars/all/cert_keys.yml"
      content: "{{ chainsmith_out.stderr }}"
  loop_control:
    label: "{{ item.dest }}"
