---
linux_pg_version: "{{ postgresql_version }}"

linux_packages:
  hacluster:
    - "postgresql{{ linux_pg_version|replace('.','') }}"
    - "postgresql{{ linux_pg_version|replace('.','') }}-server"
    - "postgresql{{ linux_pg_version|replace('.','') }}-contrib"
    - "postgresql{{ linux_pg_version|replace('.','') }}-devel"
    - "postgresql{{ linux_pg_version|replace('.','') }}-plpython3"
    - "stolon"
    - "wal-g-pg"
    - "etcd"
