---
walg_bucket_name: backup
walg_bucket_ca_file: ~/.wal-g/certs/bucket_ca.crt

# We installeren wal-g middels een rpm
walg_packages:
  - "wal-g-pg"

#walg_aws_access_key: "{{ bucket_access_key }}"
#walg_aws_secret_key: "{{ bucket_secret_key }}"
#walg_aws_endpoint: "https://{{ groups['backup'][0] }}{{ bucket_server_addr }}"
walg_pg_datadir: "{{stolon_data_dir }}/postgres"
walg_pg_bindir: "{{ postgresql_bindir }}"
walg_pg_hostname: "{{ postgresql_socketdir }}"
walg_backup_skip_window: 8
# Keep  days of backups
walg_cron_mailto: "{{ cron_mailto }}"

walg_postgresql_parameters:
  archive_command: "/opt/wal-g/scripts/archive.sh %p"
  restore_command: "/opt/wal-g/scripts/archive_restore.sh %f %p"
  archive_mode: "on"
  listen_addresses: "'*'"
  log_filename: "postgresql.log"
  log_line_prefix: " "
  max_wal_senders: "3"
  wal_level: archive

walg_bucket_cert: "{{ certs.server.chain }}"
