---
azure_control_ip: 40.113.107.40
azure_cluster_name: "{{ cluster_name }}"
# required for clean playbook
azure_resource_group: "rg_{{ azure_cluster_name }}"
# to enable cleaning
azure_allow_clean: true
# Note 1: azure_storage_account_name must be unique across all of azure, therefore using a truncated version of machine_id 
# of the ansible controlnode, which is a terrible idea for production, but at least is pseudorandom for demo purpose.
# set to another value when you mean business
# Note 2: This must be set here, since defaults of azure role is not available when running pgvillage playbook
# Note 3: using hostvars, since this requires ansible_machine_id from this controlnode
azure_storage_container: "backup{{ azure_cluster_name }}"

# For arm64 we need other vm sizes and images
azure_bastion_vm_size: Standard_D2pls_v5
azure_vmss_vm_size: Standard_D2pls_v5

#Arm64           rhel-arm64                              RedHat                                    8_6-arm64                                        RedHat:rhel-arm64:8_6-arm64:8.6.2022060901                                                                  8.6.2022060901
azure_vmss_image:
  offer: rhel-arm64
  publisher: RedHat
  sku: 8_6-arm64
  version: 8.6.2022060901

#Arm64           CentOS   OpenLogic    7_9-arm64  OpenLogic:CentOS:7_9-arm64:7.9.2022092602  7.9.2022092602
#azure_vmss_image:
#  offer: CentOS
#  publisher: OpenLogic
#  sku: 7_9-arm64
#  version: 7.9.2022092602
azure_bastion_plan: {}
azure_vmss_plan: null
#azure_vmss_plan:
#  name: "8_6-arm64"
#  product: "rhel-arm64"
#  publisher: "redhat"
